---
abstract: 'run a temporrary instance of MongoDB'
author:
  - 'Jesse Shy <jshy@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-mongod
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Config::ZOMG: 0
  File::Temp: 0
  FindBin: 0
  Hash::Merge: 0
  Net::EmptyPort: 0
  POSIX: 0
  Time::HiRes: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/jshy/Test-mongod/issues
  homepage: https://github.com/jshy/Test-mongod
  repository: https://github.com/jshy/Test-mongod.git
version: 0.02
x_contributors:
  - 'Jesse Shy <jesse@classmith.com>'
